name = "HackRecursion"
uuid = "a51924b7-bf7f-4e90-9a8a-351adcf2fc72"
authors = ["N5N3"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
